### ISSUE TITLE
Improve README / documentation.

### ISSUE THREAD

**Issue by jorgebucaran** [okwolf/cra-hyperapp#3]
This repo is kind of "special" because it's not a plugin or gizmo and closer to a boilerplate. I'm torn between whether this should be transferred back to @okwolf or kept here. In the meantime, we could improve the documentation. Perhaps use some ideas from the [Hyperapp Gizmo](https://gist.github.com/jorgebucaran/533f75c2330cf79afc2e622ad7a07e84) template. It does not need to be like every other "gizmo", but some bits from the template could be used to revamp the current README.

**Comment by okwolf** [comment]
Keeping this because the docs still need love, but obviously it's already been transferred back to me.

**Comment by jorgebucaran** [comment]
@okwolf What was this previously named?

**Comment by okwolf** [comment]
Average users should be using [`create-hyperapp`](https://github.com/okwolf/create-hyperapp) instead of this. A note has already been added to the README.
