### ISSUE TITLE
Remove / before /static/js

### ISSUE THREAD

**Issue by alber70g** [okwolf/cra-hyperapp#4]
Hi,

Thank you for your effort in creating this. It's a blaze to use it. I got two comments:

- Remove the / before /static/js in the build version index.html. I'm hosting on github pages and the urls aren't from root. Either way, the urls are relative anyway, so they can stay relative instead of absolute.
- Add a minor description on how to add stylesheets. I got it working after 5 minutes, but I first looked at the readme and found there was no description of it.

Once more, nice tool!

**Comment by okwolf** [comment]
Thanks for giving this a try!

I'm a bit confused - where is there `/static/js`? This repo doesn't even have an `index.html`. Did you mean to post this in [hyperapp-cra-example](https://github.com/okwolf/hyperapp-cra-example)?

Is there something unique to `cra-hyperapp` for CSS that's not covered by the [create-react-app](https://github.com/facebook/create-react-app) docs?

**Comment by alber70g** [comment]
When running the build there's an `index.html` generated inside the `/build` directory. This one has a reference to `/static/js/main.hash.js`. 

About the css, I ended up putting a stylesheet in the `public` directory and referencing it from the `public/index.html`. It wasn't mentioned anywhere but it worked. It might not even be the right way to do so, but for a quick hacked together project it works.

**Comment by okwolf** [comment]
For the relative paths with `create-react-app` take a look at [this](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#building-for-relative-paths).

CSS can be included from the `public` folder by adding to the `index.html` or from the `src` folder using `import` statements. The project that `create-react-app` bootstraps puts CSS in the [`src` folder](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#folder-structure).

Should we add a link to the [`create-react-app` documentation](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md) from this project? These issues don't appear to be related to this library.

**Comment by okwolf** [comment]
@Alber70g any update on this issue?

**Comment by alber70g** [comment]
> Should we add a link to the create-react-app documentation from this project? These issues don't appear to be related to this library.

If the create-react-app docs are applicable to this project, it might be a good idea. 

I have no further comments regarding this. So I'll close it.

**Comment by okwolf** [comment]
> @Alber70g If the create-react-app docs are applicable to this project, it might be a good idea.

The Quick Overview sections on the [`npm start`](https://github.com/facebook/create-react-app#npm-start-or-yarn-start), [`npm test`](https://github.com/facebook/create-react-app#npm-test-or-yarn-test), and [`npm build`](https://github.com/facebook/create-react-app#npm-run-build-or-yarn-build) scripts do apply. The [User Guide](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md) mostly applies, except for a few parts that are only relevant when using React.
